### ISSUE TITLE
error with error message

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#11]
```
uqbwoodc@mrca003:20150220:/srv/projects/abisko/shotgun_abundance/53_doe_talk_functional_gene_pca/bclA/graftm$ graftM --forward /srv/projects/abisko/data/flat20150213/20120800_S1M.1.fq.gz --search_only --threads 40 --output_stats 20120800_S1M --hmm_file ../AAN32623.1.mingle/homologs.faa.aligned.hmm  --type P
Traceback (most recent call last):
  File "/srv/sw/graftm/0.4.0/bin/graftM", line 47, in <module>
    Run(args).main()
  File "/srv/sw/graftm/0.4.0/graftm/Run.py", line 33, in __init__
    self.HK.set_attributes(self.args)
  File "/srv/sw/graftm/0.4.0/graftm/HouseKeeping.py", line 116, in set_attributes
    Messenger().message('ERROR: %s is empty or misformatted.' % args.graftm_package)
AttributeError: 'Namespace' object has no attribute 'graftm_package'
```

**Comment by geronimp** [comment]
Fixd'

Thanks,
Joel
