### ISSUE TITLE
doesn't deal with interleaved paired sequence files

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#115]
Get an error like this:
```
STDERR was: Traceback (most recent call last):
  File "/srv/whitlam/home/users/uqbwoodc/git/graftM/bin/graftM", line 233, in <module>
    Run(args).main()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 483, in main
    self.graft()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 314, in graft
    diamond_db
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/timeit.py", line 10, in timed
    result = method(*args, **kw)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/hmmer.py", line 745, in aa_db_search
    hit_reads_orfs_fasta)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/hmmer.py", line 849, in search_and_extract_orfs_matching_protein_database
    hits
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/hmmer.py", line 455, in _extract_from_raw_reads
    complement_info = self._extract_multiple_hits(hits, tmp.name, output_path)  # split them into multiple reads
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/hmmer.py", line 393, in _extract_multiple_hits
    reads = SeqIO.to_dict(SeqIO.parse(reads_path, "fasta"))  # open up reads as dictionary
  File "/srv/sw/biopython/1.63/lib/python2.7/site-packages/biopython-1.63-py2.7-linux-x86_64.egg/Bio/SeqIO/__init__.py", line 716, in to_dict
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'D8QSB6V1:137:H9FH8ADXX:1:1101:8497:3847'
STDOUT was: 
```

**Comment by wwood** [comment]
will give a better error message

**Comment by geronimp** [comment]
fixed in latest commit to branch geronimp-decorate
