### ISSUE TITLE
Error when using diamond search method

### ISSUE THREAD

**Issue by caity-s** [geronimp/graftM#130]
Hello,

Traceback error when using --search_method diamond. The command run was: graftM graft --forward /srv/projects/abisko/aterrible_bins/10_assembly73_individuals20150928/bins/*.fa --graftm_package /srv/projects/abisko/Caitlin/graftM_packages_cait/0_graftm_packages_current/20121111_nifH.gpkg/ --output_directory 20151112_nifH_diamond --search_method diamond --threads 20 --force &> nifH.log

Traceback (most recent call last):
  File "/srv/sw/graftm/dev_rochelle/bin/graftM", line 287, in <module>
    Run(args).main()
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/run.py", line 510, in main
    self.graft()
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/run.py", line 322, in graft
    diamond_db
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/timeit.py", line 10, in timed
    result = method(*args, **kw)
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/hmmer.py", line 803, in aa_db_search
    hit_reads_orfs_fasta)
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/hmmer.py", line 931, in search_and_extract_orfs_matching_protein_database
    SequenceSearchResult.QUERY_TO_FIELD])
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/hmmer.py", line 592, in _extract_orfs
    entry=sequence_frame_info_dict[record.id]
KeyError: 'contig_8516_split_1'

Thanks,
Caitlin

**Comment by wwood** [comment]
Joel's favourite error! Thanks for the quality bug report.
