### ISSUE TITLE
Error with graftM graft --for/rev/merge when reads in forward but not reverse 

### ISSUE THREAD

**Issue by caity-s** [geronimp/graftM#132]
Hello,

Seems that if only a few reads are picked up, and if they are found only in the forward (or only in the reverse) then it crashes. If reads are found in both the forward and reverse it's fine, if no reads are found in either it's also fine. 

Command: ls /srv/projects/abisko/data/flat20150213/ | grep .1.fq.gz | sed 's/.1.fq.gz//g'| parallel -j5 graftM graft --forward /srv/projects/abisko/data/flat20150213/{}.1.fq.gz --reverse /srv/projects/abisko/data/flat20150213/{}.2.fq.gz --merge_reads --graftm_package /srv/projects/abisko/Caitlin/graftM_packages_cait/0_graftm_packages_current/20121111_archaeal_amoA.gpkg --threads 4 --force --output_directory {} &> archaea.log ; finish

Traceback:
11/12/2015 05:34:34 PM INFO: Working on 20110600_E1M.1
11/12/2015 05:34:34 PM INFO: Working on forward reads
11/12/2015 05:36:25 PM INFO: 2 read(s) detected
11/12/2015 05:36:25 PM INFO: Aligning reads to reference package database
11/12/2015 05:36:25 PM INFO: Filtered 0 short sequences from the alignment
11/12/2015 05:36:25 PM INFO: 2 sequences remaining
11/12/2015 05:36:25 PM INFO: Working on reverse reads
11/12/2015 05:38:23 PM INFO: No reads found in 20110600_E1M.1
Traceback (most recent call last):
  File "/srv/sw/graftm/dev_rochelle/bin/graftM", line 287, in <module>
    Run(args).main()
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/run.py", line 510, in main
    self.graft()
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/run.py", line 408, in graft
    seqs_list=C.cluster(seqs_list, REVERSE_PIPE)
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/clusterer.py", line 83, in cluster
    reads=self.seqio.read_fasta_file(input_fasta) # Read in FASTA records
  File "/srv/sw/graftm/dev_rochelle/bin/../graftm/sequence_io.py", line 44, in read_fasta_file
    for name, seq, _ in self._readfq(open(path_to_fasta_file)):
IOError: [Errno 2] No such file or directory: '20110600_E1M/20110600_E1M.1/20110600_E1M.1_hits.aln.fa'

Thanks!
Caitlin

**Comment by fsepulveda-ubiome** [comment]
I got the same problem :(
