### ISSUE TITLE
graftm create --graftm_package is a bit picky

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#178]
```
uqbwoodc@curtin:20160131:/srv/projects/abisko/shotgun_abundance/103_contig_tree_relative_abundances/1_test$ ~/git/graftM/bin/graftM create --graftm_package another.gpkg/ --taxonomy /tmp/mytax2 --sequences another.gpkg/2.16.ribosomal_protein_S5_seqs_clus_97.faa
                         
                             GraftM 0.9.4
01/31/2016 10:00:05 PM WARNING: Program found with multiple commands: taxit FastTreeMP seqmagick hmmalign mafft. Arbitrarily selecting FastTreeMP

                            CREATE

                   Joel Boyd, Ben Woodcroft

                                                    /
              >a                                   /
              -------------                       /
              >b                        |        |
              --------          >>>     |  GPKG  |
              >c                        |________|
              ----------

01/31/2016 10:00:05 PM INFO: GraftM package another.gpkg/ specified to update with sequences in another.gpkg/2.16.ribosomal_protein_S5_seqs_clus_97.faa
Traceback (most recent call last):
  File "/srv/whitlam/home/users/uqbwoodc/git/graftM/bin/graftM", line 346, in <module>
    Run(args).main()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 563, in main
    raise UnrecognisedSuffixError("Unrecognised suffix on GraftM package %s. Please provide a graftM package with the correct suffix (.gpkg)" % (self.args.graftm_package))
graftm.run.UnrecognisedSuffixError: Unrecognised suffix on GraftM package another.gpkg/. Please provide a graftM package with the correct suffix (.gpkg)
```
I think the root of this issue is that 'update' shouldn't be a thing, rather, it should be used as a convenience method to specify the things required to build a new package (taxtastic taxonomy/seqinfo, sequences, rooted tree, that all?), but defer to other command line parameters e.g. if rerooted_annotated_tree is given, get the tree and the taxonomy from that.

Also, the warning looks not right:
```
01/31/2016 10:00:05 PM WARNING: Program found with multiple commands: taxit FastTreeMP seqmagick hmmalign mafft. Arbitrarily selecting FastTreeMP
```

Thanks.

**Comment by wwood** [comment]
closing since this is discussed elsewhere e.g. #129
