### ISSUE TITLE
Cannot specify diamond database when using --search_only option

### ISSUE THREAD

**Issue by geronimp** [geronimp/graftM#198]
e.g.

```
graftM graft --forward reads.fa --search_diamond_file my.dmnd --search_only

                             GraftM 0.9.3
Traceback (most recent call last):
  File "/srv/sw/graftm/0.9.3/bin/graftM", line 345, in <module>
    Run(args).main()
  File "/srv/sw/graftm/0.9.3/bin/../graftm/run.py", line 41, in __init__
    self.setattributes(self.args)
  File "/srv/sw/graftm/0.9.3/bin/../graftm/run.py", line 52, in setattributes
    self.hk.set_attributes(self.args)
  File "/srv/sw/graftm/0.9.3/bin/../graftm/housekeeping.py", line 195, in set_attributes
    raise Exception('No refpkg or HMM specified: Do not know what to search with.')
Exception: No refpkg or HMM specified: Do not know what to search with.
```

**Comment by geronimp** [comment]
I'll fix this.

**Comment by wwood** [comment]
thanks. I take it it is the same in graftM bleeding edge.

**Comment by geronimp** [comment]
fixed in https://github.com/geronimp/graftM/pull/239
