### ISSUE TITLE
graftm tree GreenGenesTaxonomy exceptions are covered up

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#226]
Running something like this:

```
bash-4.3$ ~/git/graftM/bin/graftM tree --decorate --rooted_tree decorated.rerooted.tree --input_greengenes_taxonomy /srv/projects/abisko/annotation/18_aterrible12_prokka_to_KO/aterrible12_s5_graftm.autotaxonomy --output_tree decorated.rerooted.autotaxonomy_decorated.tree --output_taxonomy decorated.rerooted.autotaxonomy_decorated.taxonomy 

                             GraftM 0.9.5
09/23/2016 02:54:44 PM INFO: Reading in taxonomy
09/23/2016 02:54:44 PM INFO: Reading Greengenes style taxonomy
Traceback (most recent call last):
  File "/home/ben/git/graftM/bin/graftM", line 419, in <module>
    Run(args).main()
  File "/home/ben/git/graftM/bin/../graftm/run.py", line 733, in main
    self.args.no_unique_tax, self.args.decorate, None) 
  File "/home/ben/git/graftM/bin/../graftm/decorator.py", line 78, in main
    seqinfo)
  File "/home/ben/git/graftM/bin/../graftm/tree_decorator.py", line 74, in __init__
    taxonomy provided with no seqinfo file?")
Exception: Failed to read taxonomy as a Greengenes                                  formatted file. Was a taxtastic style                                  taxonomy provided with no seqinfo file?
```

The problem isn't with that I've forgotten to specify a seqinfo file. The real issue is that some lineages had their taxonomy specified twice in the taxonomy file. This causes a `MalformedGreenGenesTaxonomyException` to be raised. An improvement would be raising a different kind of exception when `line.split("\t")` returns an array with 1 entry, and only catching that different exception in `tree_decorator.py`.

Also the spacing is odd in the exception.

This is bit size but I don't quite have time right now.

**Comment by wwood** [comment]
pwd is `/srv/projects/abisko/aterrible_bins/12_assembly73_individuals_flat20160115/gtdb/tree_bacterial_set` btw
