### ISSUE TITLE
HMMsearch + DIAMOND 

### ISSUE THREAD

**Issue by ljmmm** [geronimp/graftM#236]
Hey guys,

Great tool, thanks for sharing.

When running graftM graft on some bins (--search_method hmmsearch+diamond, mcra package), I get the output below. Geronimp suggested that the DIAMOND search has filtered out all reads but the pipeline still marches on.

05/05/2017 10:15:00 AM INFO: Working on oscar_grouch_bin
05/05/2017 10:15:00 AM INFO: 1 read(s) detected
Error: Unexpected end of file.
Traceback (most recent call last):
  File "/gnu/store/wmqyh831hzcxfsmsxq1mizdi1jcjz0ad-graftm-0.10.1/bin/..graftM-real-real", line 444, in <module>
    Run(args).main()
  File "/gnu/store/wmqyh831hzcxfsmsxq1mizdi1jcjz0ad-graftm-0.10.1/lib/python2.7/site-packages/graftm/run.py", line 588, in main
    self.graft()
  File "/gnu/store/wmqyh831hzcxfsmsxq1mizdi1jcjz0ad-graftm-0.10.1/lib/python2.7/site-packages/graftm/run.py", line 417, in graft
    tmpname)
  File "/gnu/store/wmqyh831hzcxfsmsxq1mizdi1jcjz0ad-graftm-0.10.1/lib/python2.7/site-packages/graftm/decoy_filter.py", line 44, in filter
    UnpackRawReads.PROTEIN_SEQUENCE_TYPE)
  File "/gnu/store/wmqyh831hzcxfsmsxq1mizdi1jcjz0ad-graftm-0.10.1/lib/python2.7/site-packages/graftm/diamond.py", line 62, in run
    res = DiamondSearchResult.import_from_daa_file(daa_name)
  File "/gnu/store/wmqyh831hzcxfsmsxq1mizdi1jcjz0ad-graftm-0.10.1/lib/python2.7/site-packages/graftm/sequence_search_results.py", line 90, in import_from_daa_file
    "stderr was %s" % (cmd, stderr))
Exception: Problem running diamond view with cmd: 'diamond view -a '/tmp/graftm_diamond4jOMpN.daa'',stderr was None

Thanks!

Louis.

**Comment by geronimp** [comment]
Thanks Louis,

Looks like that read was filtered, but the pipeline failed to catch that there were no reads to continue with.

We'll implement a more graceful error message in an upcoming release.

Thanks,  

Joel

**Comment by geronimp** [comment]
@wwood Were you working on this one?

**Comment by wwood** [comment]
Nope, go ahead
