### ISSUE TITLE
Error: TC bit thresholds unavailable on model graftmrzdqhx.aln

### ISSUE THREAD

**Issue by sarah872** [geronimp/graftM#264]
I am trying to create a package but I am getting an error during the testing phase:

```
$ graftM create --sequences test3.fasta --taxonomy gg_13_5_taxonomy.txt --hmm nifH_TIGR01287.HMM

                             GraftM 0.12.2
12/23/2019 12:01:27 PM WARNING: Program found with multiple commands: taxit FastTreeMP hmmalign mafft. Arbitrarily selecting FastTreeMP

                            CREATE

                   Joel Boyd, Ben Woodcroft

                                                    /
              >a                                   /
              -------------                       /
              >b                        |        |
              --------          >>>     |  GPKG  |
              >c                        |________|
              ----------

12/23/2019 12:01:27 PM INFO: Building gpkg for test3.gpkg
12/23/2019 12:01:27 PM INFO: Building seqinfo and taxonomy file from input taxonomy
12/23/2019 12:01:37 PM INFO: Checking for duplicate sequences
12/23/2019 12:01:37 PM INFO: Aligning sequences to create aligned FASTA file
12/23/2019 12:01:39 PM INFO: Filtered 0 short sequences from the alignment
12/23/2019 12:01:39 PM INFO: 59 sequences remaining
12/23/2019 12:01:39 PM INFO: Checking for incorrect or fragmented reads
12/23/2019 12:01:40 PM INFO: Building HMM from alignment
12/23/2019 12:01:41 PM INFO: Filtered 0 short sequences from the alignment
12/23/2019 12:01:41 PM INFO: 59 sequences remaining
12/23/2019 12:01:41 PM INFO: Deduplicating sequences
12/23/2019 12:01:41 PM INFO: Removed 3 sequences as duplicates, leaving 56 non-identical sequences
12/23/2019 12:01:41 PM INFO: Building tree
12/23/2019 12:01:43 PM INFO: Building seqinfo and taxonomy file from input taxonomy
12/23/2019 12:01:59 PM INFO: Creating reference package
12/23/2019 12:01:59 PM INFO: Attempting to run taxit create with rerooting capabilities
12/23/2019 12:02:00 PM INFO: Creating diamond database
12/23/2019 12:02:00 PM INFO: Compiling gpkg
12/23/2019 12:02:01 PM INFO: Cleaning up
12/23/2019 12:02:01 PM INFO: Testing gpkg package works
Traceback (most recent call last):
  File "/home/user/py2-venv/bin/graftM", line 411, in <module>
    Run(args).main()
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/run.py", line 661, in main
    threads = self.args.threads
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/create.py", line 856, in main
    self._test_package(output_gpkg_path)
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/create.py", line 537, in _test_package
    extern.run(cmd)
  File "/home/user/py2-venv/lib/python2.7/site-packages/extern/__init__.py", line 46, in run
    stdout)
extern.ExternCalledProcessError: Command graftM graft --forward /tmp/tmpL6stk0.fa --graftm_package test3.gpkg --output_directory /tmp/tmpHsjAc4 --force returned non-zero exit status 1.
STDERR was: 12/23/2019 12:02:02 PM INFO: Working on tmpL6stk0
Traceback (most recent call last):
  File "/home/user/py2-venv/bin/graftM", line 411, in <module>
    Run(args).main()
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/run.py", line 592, in main
    self.graft()
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/run.py", line 377, in graft
    diamond_db
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/timeit.py", line 10, in timed
    result = method(*args, **kw)
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/sequence_searcher.py", line 821, in aa_db_search
    hit_reads_orfs_fasta)
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/sequence_searcher.py", line 883, in search_and_extract_orfs_matching_protein_database
    orfm
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/sequence_searcher.py", line 220, in hmmsearch
    searcher.hmmsearch(input_cmd, self.search_hmm, output_table_list)
  File "/home/user/py2-venv/lib/python2.7/site-packages/graftm/hmmsearcher.py", line 69, in hmmsearch
    raise e
extern.ExternCalledProcessError: Command cat /tmp/tmpL6stk0.fa | hmmsearch --cut_tc --cpu 5 -o /dev/null --noali --domtblout /tmp/tmpHsjAc4/tmpL6stk0/tmpL6stk0.hmmout.txt test3.gpkg/graftmIHLFTV_search.hmm - returned non-zero exit status 1.
STDERR was:
Error: TC bit thresholds unavailable on model graftmrzdqhx.aln

STDOUT was:
STDOUT was:
                             GraftM 0.12.2

                                GRAFT

                       Joel Boyd, Ben Woodcroft

                                                         __/__
                                                  ______|
          _- - _                         ________|      |_____/
           - -            -             |        |____/_
           - _     >>>>  -   >>>>   ____|
          - _-  -         -             |      ______
             - _                        |_____|
           -                                  |______


```

**Comment by wwood** [comment]
Hi,

Apologies for the delay. I believe this is caused by the HMM `nifH_TIGR01287.HMM` you are using, would you mind pasting that as a GitHub gist or something along those lines so I can have a look please?

Thanks.

**Comment by sarah872** [comment]
It's an HMM from the TIGRFAM servers.
[nifH_TIGR01287.HMM.txt](https://github.com/geronimp/graftM/files/4044513/nifH_TIGR01287.HMM.txt)
