### ISSUE TITLE
Issue running graftm create using docker

### ISSUE THREAD

**Issue by erins1** [geronimp/graftM#268]
Hi,

I am a new user of graftM. Running using docker.
When I try to run graftM create to build a package I receive the following errors.

`> docker run -v pwd:/data wwood/graftm:v0.13.1 create --sequences /Users/e/Documents/graftm_test/bsh_sequences.fasta --taxonomy /Users/e/Documents/graftm_test/bsh_taxonomy_file2.txt --output bsh_graftm_package.gpkg --log bsh_log.txt`
Traceback (most recent call last):
File "/gnu/store/jcxdrw6c6z7n9q9wwqjyirk0lxgm715x-graftm-0.13.1/bin/.graftM-real", line 415, in
Run(args).main()
File "/gnu/store/jcxdrw6c6z7n9q9wwqjyirk0lxgm715x-graftm-0.13.1/lib/python3.7/site-packages/graftm/run.py", line 681, in main
threads = self.args.threads
File "/gnu/store/jcxdrw6c6z7n9q9wwqjyirk0lxgm715x-graftm-0.13.1/lib/python3.7/site-packages/graftm/create.py", line 593, in main
taxonomy_definition = GreenGenesTaxonomy.read_file(taxonomy).taxonomy
File "/gnu/store/jcxdrw6c6z7n9q9wwqjyirk0lxgm715x-graftm-0.13.1/lib/python3.7/site-packages/graftm/greengenes_taxonomy.py", line 51, in read_file
with open(input_filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/e/Documents/graftm_test/bsh_taxonomy_file2.txt'

Even though the file clearly is in my current working directory:
Directory: C:\Users\e\Documents\graftm_test> ls
Mode LastWriteTime Length Name
-a---- 28/10/2020 10:48 AM 214479 bsh_sequences.fasta
-a---- 28/10/2020 12:05 PM 27362 bsh_taxonomy_file1.txt
-a---- 28/10/2020 1:55 PM 27362 bsh_taxonomy_file2.txt

Happens whether I run this on PC or MAC.

Including `--user $(id -u):$(id -g)` doesn't change anything other than generating the additional error "The term 'id' is not recognized as the name of a cmdlet, function, script file, or operable program."

Thanks for any help in understanding how to overcome this error.
(I've also posted on GraftM-docker page but doesn't look like there has been any action there for a while).
Erin

**Comment by wwood** [comment]
Hi Erin,

Does removing the `/Users/e/Documents/graftm_test/` bit from before `bsh_taxonomy_file2.txt` help in the docker run? I suspect that directory isn't the same inside docker as it is outside. Could be wrong tho.

**Comment by erins1** [comment]
Hi,
Thanks for the very rapid response.
No, it doesn't change anything, generates the same error message.
I've tried playing around with adding --workdir so that I can set a specific working directory inside but that also doesn't seem to help.

Thanks,
Erin

**Comment by wwood** [comment]
Np.

I see you only had `pwd` not '\`pwd\`` as was intended. Not sure if that helps.

The other thing to consider here is that the docker releases have fallen behind, for boring technical reasons. It is probably more straightforward to use conda, if possible?

**Comment by aljazdzy** [comment]
> Np.
> 
> I see you only had `pwd` not pwd surrounded by ` as was intended. Not sure if that helps.
> 
> The other thing to consider here is that the docker releases have fallen behind, for boring technical reasons. It is probably more straightforward to use conda, if possible?

Whenever I attempt to install with conda it's unable to find any of the dependencies, and installing the dependencies separately has been a real hassle (I've thus failed)

**Comment by wwood** [comment]
Hi,

What dependency is causing problems? I think the conda recipe might be incomplete but dependencies missing can still be installed through bioconda?

**Comment by aljazdzy** [comment]
> Hi,
> 
> What dependency is causing problems? I think the conda recipe might be incomplete but dependencies missing can still be installed through bioconda?

I ended up figuring out the issue, basically the issue was as simple as I needed to be installing through the linux version of conda instead of the windows version of conda - I'm rather new at this type of analysis so I'm still learning!
