### ISSUE TITLE
Getting ZeroDivisionError when running with sample data

### ISSUE THREAD

**Issue by MelodyMale** [geronimp/graftM#275]
I tried this command `graftM graft --forward sample_mcrA_1.fa sample_mcrA_2.fa --graftm_package 7.27.methyl_coenzyme_reductase_alpha_subunit.mcrA.gpkg`
and got this error
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graftM/bin/graftM", line 415, in <module>
    Run(args).main()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graftM/lib/python3.6/site-packages/graftm/run.py", line 613, in main
    self.graft()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graftM/lib/python3.6/site-packages/graftm/run.py", line 388, in graft
    diamond_db
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graftM/lib/python3.6/site-packages/graftm/timeit.py", line 10, in timed
    result = method(*args, **kw)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graftM/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 851, in aa_db_search
    hit_reads_orfs_fasta)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graftM/lib/python3.6/site-packages/graftm/sequence_searcher.py", line 905, in search_and_extract_orfs_matching_protein_database
    unpack.sequence_type(),
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graftM/lib/python3.6/site-packages/graftm/unpack_sequences.py", line 92, in sequence_type
    self.type = self._guess_sequence_type_from_string(seq)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graftM/lib/python3.6/site-packages/graftm/unpack_sequences.py", line 74, in _guess_sequence_type_from_string
    if float(num_protein) / (num_protein+num_nucleotide) > 0.1:
ZeroDivisionError: float division by zero
```
Do you have any suggestions?
Thank you

**Comment by wwood** [comment]
Hi,

Looks to me like there is something wrong with your mfqe installation. Maybe try install through conda instead of downloading the linux-musl version (or compiling it from scratch), since you are on OSX rather than linux, I think.

**Comment by MelodyMale** [comment]
@wwood 
Thanks for replying

I tried to install from conda but there is no osx version.

**Comment by wwood** [comment]
Ah, right. I tried pushing mfqe to conda for OSX but initial attempts failed. That might require some debugging.

I don't immediately have access to an OSX box. Would you be able to try compiling mfqe from source? You just clone the repo at https://github.com/wwood/mfqe , cd mfqe, then `cargo build --release`. You'll need to install rust too, which you can from the instructions at https://www.rust-lang.org/tools/install

Or, you could wait for me to get to it. Not sure when that will be though, sorry.

**Comment by MelodyMale** [comment]
@wwood 
Thank you for your suggestion. I tried to build with cargo and it worked. 🙏🏻
