### ISSUE TITLE
doesn't fail gracefully when an old version of hmmer is used

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#37]
from @fauziharoon running 3.0:
```
$ graftM graft --forward ../prinseq_trimmed_metagenome_reads/sample01.1.prinseq.fasta --threads 20 --graftm_package ~/DB/graftm_packages/16S_82_hmmaligned_gpkg

                                GRAFT

                       Joel Boyd, Ben Woodcroft

                                                         __/__
                                                  ______|
          _- - _                         ________|      |_____/
           - -            -             |        |____/_
           - _     >>>>  -   >>>>   ____|
          - _-  -         -             |      ______
             - _                        |_____|
           -                                  |______


[14:49:20]: Working on sample01
        06-05-2015  [14:49:20]: Searching sample01.1.prinseq.fasta
        06-05-2015  [14:49:45]: 5389 read(s) found
        06-05-2015  [14:49:53]: Aligning reads to reference package database

ERROR: File /home/haroonmf/DB/graftm_packages/16S_82_hmmaligned_gpkg/82.hmm does not appear to be in a recognized HMM format.
Usage: hmmalign [-options] <hmmfile> <seqfile>

To see more help on available options, do hmmalign -h


ERROR: File /home/haroonmf/DB/graftm_packages/16S_82_hmmaligned_gpkg/82.hmm does not appear to be in a recognized HMM format.
Usage: hmmalign [-options] <hmmfile> <seqfile>

To see more help on available options, do hmmalign -h


[14:49:54]: Placing reads into phylogenetic tree
Sequence length cut to 0 by pre-masking; can't proceed with no information.
Traceback (most recent call last):
  File "/usr/local/bin/graftM", line 152, in <module>
    Run(args).main()
  File "/usr/local/lib/python2.7/dist-packages/graftm/run.py", line 396, in main
    self.graft()
  File "/usr/local/lib/python2.7/dist-packages/graftm/run.py", line 338, in graft
    self.placement(summary_table)
  File "/usr/local/lib/python2.7/dist-packages/graftm/run.py", line 127, in placement
    self.args)
  File "/usr/local/lib/python2.7/dist-packages/graftm/pplacer.py", line 89, in place
    jplace = self.pplacer(files.jplace_output_path(), args.output_directory, files.comb_aln_fa(), args.threads, files.command_log_path())
  File "/usr/local/lib/python2.7/dist-packages/graftm/pplacer.py", line 28, in pplacer
    subprocess.check_call(cmd, shell=True) # Run it
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pplacer -j 20 --verbosity 0 --out-dir GraftM_output -c /home/haroonmf/DB/graftm_packages/16S_82_hmmaligned_gpkg/82.refpkg GraftM_output/combined_alignment.aln.fa' returned non-zero exit status 1
```

**Comment by geronimp** [comment]
This fails at the external_program_suite check stage now
