### ISSUE TITLE
missing file from repo?

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#48]
got this error, does it need to be git added?
```
$ nosetests -x
Traceback (most recent call last):
  File "/home/ben/git/graftM/test/../bin/graftM", line 166, in <module>
    Run(args).main()
  File "/home/ben/git/graftM/bin/../graftm/run.py", line 22, in __init__
    self.setattributes(self.args)
  File "/home/ben/git/graftM/bin/../graftm/run.py", line 31, in setattributes
    self.hk.set_attributes(self.args)
  File "/home/ben/git/graftM/bin/../graftm/housekeeping.py", line 211, in set_attributes
    raise Exception("%s does not exist. Are you sure you provided the correct path?" % args.graftm_package)
Exception: /home/ben/git/graftM/test/data/61_otus.gpkg does not exist. Are you sure you provided the correct path?
E
======================================================================
ERROR: test_concatenated_OTU_table (test_graftm.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/git/graftM/test/test_graftm.py", line 738, in test_concatenated_OTU_table
    subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '/home/ben/git/graftM/test/../bin/graftM graft --forward /home/ben/git/graftM/test/sample_runs/sample_16S_1.1.fa /home/ben/git/graftM/test/sample_runs/sample_16S_2.1.fa --graftm_package /home/ben/git/graftM/test/data/61_otus.gpkg --output_directory /tmp/tmpj9C7Fe --force' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 1 test in 0.092s

FAILED (errors=1)
```

**Comment by geronimp** [comment]
Yes, my bad

**Comment by wwood** [comment]
fixed
