### ISSUE TITLE
graftm create should create a HMM when an alignment is provided

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#51]
```
s4383937@mrca002:~/mingle/mtd$ ~uqbwoodc/git/graftM/bin/graftM create --taxonomy homologs.tax2tree.rerooted.decorated.tree-consensus-strings --alignment homologs.trimmed.aligned.faa --tree the.tree --tree_log homologs.tree.log --output mtd.gpkg

                            CREATE

                   Joel Boyd, Ben Woodcroft
                     
                                                    /                
              >a                                   /
              -------------                       /            
              >b                        |        |
              --------          >>>     |  GPKG  |
              >c                        |________|
              ----------     

05/29/2015 02:51:09 PM INFO: Building gpkg for homologs
05/29/2015 02:51:09 PM INFO: Building seqinfo and taxonomy file
05/29/2015 02:51:09 PM INFO: Creating reference package
warning: rank species not represented in the lineage of any sequence in reference package mtd.gpkg.
05/29/2015 02:51:10 PM INFO: Compiling gpkg
Traceback (most recent call last):
  File "/srv/whitlam/home/users/uqbwoodc/git/graftM/bin/graftM", line 174, in <module>
    graftm.run.Run(args).main()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 403, in main
    self.args.taxonomy, self.args.tree, self.args.tree_log, self.args.output)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/create.py", line 181, in main
    self.compile(base, refpkg, hmm, contents, prefix)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/create.py", line 108, in compile
    shutil.copyfile(hmm, os.path.join(gpkg, os.path.basename(hmm)))
  File "/srv/sw/python/2.7.4/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by wwood** [comment]
Now works in create
