### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#92]
Any ideas?
```
uqbwoodc@keating:20150806:/tmp$ PATH=~/git/graftM/bin:$PATH graftM graft --threads 15 --forward /srv/projects/share/for_Joel/bin55.fa  --search_hmm_files /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_L11_rplK_gpkg/DNGNGWU00024.hmm /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S17_gpkg/DNGNGWU00036.hmm --search_and_align_only --aln_hmm_file /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm --verbosity 5 --input_sequence_type nucleotide
                         
                             GraftM 0.7.0

                                GRAFT

                       Joel Boyd, Ben Woodcroft

                                                         __/__
                                                  ______|
          _- - _                         ________|      |_____/
           - -            -             |        |____/_
           - _     >>>>  -   >>>>   ____|
          - _-  -         -             |      ______
             - _                        |_____|
           -                                  |______
            
08/06/2015 03:27:27 PM DEBUG: Creating working directory: GraftM_output
08/06/2015 03:27:27 PM DEBUG: HMM type: P Trusted Cutoff: None
08/06/2015 03:27:27 PM DEBUG: Working with 1 file(s)
08/06/2015 03:27:27 PM INFO: Working on bin55
08/06/2015 03:27:27 PM DEBUG: Running protein pipeline
08/06/2015 03:27:27 PM DEBUG: Detected file format FORMAT_FASTA
08/06/2015 03:27:27 PM DEBUG: raw read unpacking command chunk: cat /srv/projects/share/for_Joel/bin55.fa
08/06/2015 03:27:27 PM DEBUG: Detected sequence type as nucleotide
08/06/2015 03:27:27 PM DEBUG: Using 3 HMMs to search
08/06/2015 03:27:27 PM DEBUG: OrfM command chunk: orfm  -m 96 /srv/projects/share/for_Joel/bin55.fa
08/06/2015 03:27:27 PM DEBUG: Running command: orfm  -m 96 /srv/projects/share/for_Joel/bin55.fa | tee >(hmmsearch -E 1e-5 --cpu 5 -o /dev/null --noali --domtblout GraftM_output/bin55/DNGNGWU00001_bin55.hmmout.csv /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm -) | tee >(hmmsearch -E 1e-5 --cpu 5 -o /dev/null --noali --domtblout GraftM_output/bin55/DNGNGWU00024_bin55.hmmout.csv /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_L11_rplK_gpkg/DNGNGWU00024.hmm -) | hmmsearch -E 1e-5 --cpu 5 -o /dev/null --noali --domtblout GraftM_output/bin55/DNGNGWU00036_bin55.hmmout.csv /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S17_gpkg/DNGNGWU00036.hmm -
08/06/2015 03:27:27 PM DEBUG: Running commandeer cmd: orfm  -m 96 /srv/projects/share/for_Joel/bin55.fa | tee >(hmmsearch -E 1e-5 --cpu 5 -o /dev/null --noali --domtblout GraftM_output/bin55/DNGNGWU00001_bin55.hmmout.csv /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm -) | tee >(hmmsearch -E 1e-5 --cpu 5 -o /dev/null --noali --domtblout GraftM_output/bin55/DNGNGWU00024_bin55.hmmout.csv /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_L11_rplK_gpkg/DNGNGWU00024.hmm -) | hmmsearch -E 1e-5 --cpu 5 -o /dev/null --noali --domtblout GraftM_output/bin55/DNGNGWU00036_bin55.hmmout.csv /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S17_gpkg/DNGNGWU00036.hmm -
08/06/2015 03:27:28 PM DEBUG: Running commandeer cmd: fxtract -H -X -f /tmp/graftm_readnamesEuAr3x  /srv/projects/share/for_Joel/bin55.fa > /tmp/_raw_extracted_reads.faxZiXui
08/06/2015 03:27:28 PM DEBUG: OrfM command chunk: orfm  -m 96 
08/06/2015 03:27:28 PM DEBUG: Running commandeer cmd: orfm  -m 96  GraftM_output/bin55/bin55_hits.fa > /tmp/orf_hmmsearchGbkFoo
08/06/2015 03:27:28 PM DEBUG: Running command: cat /tmp/orf_hmmsearchGbkFoo | hmmsearch  --cpu 1 -o /dev/null --noali --domtblout /tmp/orf_hmmsearchqxbmux /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm -
08/06/2015 03:27:28 PM DEBUG: Running commandeer cmd: cat /tmp/orf_hmmsearchGbkFoo | hmmsearch  --cpu 1 -o /dev/null --noali --domtblout /tmp/orf_hmmsearchqxbmux /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm -
08/06/2015 03:27:28 PM DEBUG: Running command: cat /tmp/orf_hmmsearchGbkFoo | hmmsearch  --cpu 1 -o /dev/null --noali --domtblout /tmp/orf_hmmsearchdlJsCs /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_L11_rplK_gpkg/DNGNGWU00024.hmm -
08/06/2015 03:27:28 PM DEBUG: Running commandeer cmd: cat /tmp/orf_hmmsearchGbkFoo | hmmsearch  --cpu 1 -o /dev/null --noali --domtblout /tmp/orf_hmmsearchdlJsCs /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_L11_rplK_gpkg/DNGNGWU00024.hmm -
08/06/2015 03:27:28 PM DEBUG: Running command: cat /tmp/orf_hmmsearchGbkFoo | hmmsearch  --cpu 1 -o /dev/null --noali --domtblout /tmp/orf_hmmsearchzknwr5 /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S17_gpkg/DNGNGWU00036.hmm -
08/06/2015 03:27:28 PM DEBUG: Running commandeer cmd: cat /tmp/orf_hmmsearchGbkFoo | hmmsearch  --cpu 1 -o /dev/null --noali --domtblout /tmp/orf_hmmsearchzknwr5 /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S17_gpkg/DNGNGWU00036.hmm -
08/06/2015 03:27:28 PM DEBUG: Running commandeer cmd: fxtract -H -X -f /tmp/orf_titles8DbenX /tmp/orf_hmmsearchGbkFoo > GraftM_output/bin55/bin55_orf.fa
08/06/2015 03:27:28 PM INFO: Aligning reads to reference package database
Traceback (most recent call last):
  File "/srv/whitlam/home/users/uqbwoodc/git/graftM/bin/graftM", line 231, in <module>
    graftm.run.Run(args).main()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 394, in main
    self.graft()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 319, in graft
    self._get_sequence_directions(result.search_result)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/timeit.py", line 10, in timed
    result = method(*args, **kw)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/hmmer.py", line 917, in align
    directions)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/hmmer.py", line 64, in hmmalign
    if directions[read_id] == True:
KeyError: 'bin55_contig_12071_22985_5_390'
```
then
```
uqbwoodc@keating:20150806:/tmp$ grep contig_12071 GraftM_output/bin55/*
GraftM_output/bin55/bin55_hits.fa:>bin55_contig_12071
GraftM_output/bin55/bin55_orf.fa:>bin55_contig_12071_22438_4_386
GraftM_output/bin55/bin55_orf.fa:>bin55_contig_12071_22985_5_390
GraftM_output/bin55/DNGNGWU00001_bin55.hmmout.csv:bin55_contig_12071_22438_4_386 -            310 DNGNGWU00001         -            250   4.9e-96  318.4   0.1   1   1   8.6e-99   6.8e-96  317.9   0.1    21   239    25   243    20   270 0.96 -
```
So not a hit, but still translated.

**Comment by geronimp** [comment]
Hey this is really wierd. I just started getting this bug on runs that were working perfectly fine before. reaaallly annoying. Do you want me to look into it?

________________________________

**Comment by geronimp** [comment]
and no ideas, no, this just randomly started happening.

________________________________

**Comment by geronimp** [comment]
something went wrong when you merged with master, because it doesnt have my changes from fxtract stdin. Id say thats what is happening.



________________________________

**Comment by wwood** [comment]
OK I'll check it out

**Comment by wwood** [comment]
For some reason I'd just not merged your fxtract branch into master. All fixed now, problem goes away.
