### ISSUE TITLE
missing sequences bug

### ISSUE THREAD

**Issue by wwood** [geronimp/graftM#93]
```
$ PATH=~/git/graftM/bin:$PATH graftM graft --threads 15 --verbosity 2 --forward /srv/projects/share/for_Joel/AB_C2_C3_C4_comb_assembly_bin4_hits.fa --graftm_package /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg --output_directory /tmp/outer --input_sequence_type nucleotide --force --verbosity 5
                         
                             GraftM 0.7.0

                                GRAFT

                       Joel Boyd, Ben Woodcroft

                                                         __/__
                                                  ______|
          _- - _                         ________|      |_____/
           - -            -             |        |____/_
           - _     >>>>  -   >>>>   ____|
          - _-  -         -             |      ______
             - _                        |_____|
           -                                  |______
            
08/07/2015 11:05:41 AM DEBUG: Creating working directory: /tmp/outer
08/07/2015 11:05:41 AM DEBUG: HMM type: P Trusted Cutoff: None
08/07/2015 11:05:41 AM DEBUG: Working with 1 file(s)
08/07/2015 11:05:41 AM INFO: Working on AB_C2_C3_C4_comb_assembly_bin4_hits
08/07/2015 11:05:41 AM DEBUG: Running protein pipeline
08/07/2015 11:05:41 AM DEBUG: Detected file format FORMAT_FASTA
08/07/2015 11:05:41 AM DEBUG: raw read unpacking command chunk: cat /srv/projects/share/for_Joel/AB_C2_C3_C4_comb_assembly_bin4_hits.fa
08/07/2015 11:05:41 AM DEBUG: Detected sequence type as nucleotide
08/07/2015 11:05:41 AM DEBUG: Using 1 HMMs to search
08/07/2015 11:05:41 AM DEBUG: OrfM command chunk: orfm  -m 96 /srv/projects/share/for_Joel/AB_C2_C3_C4_comb_assembly_bin4_hits.fa
08/07/2015 11:05:41 AM DEBUG: Running command: orfm  -m 96 /srv/projects/share/for_Joel/AB_C2_C3_C4_comb_assembly_bin4_hits.fa | hmmsearch -E 1e-5 --cpu 15 -o /dev/null --noali --domtblout /tmp/outer/AB_C2_C3_C4_comb_assembly_bin4_hits/AB_C2_C3_C4_comb_assembly_bin4_hits.hmmout.csv /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm -
08/07/2015 11:05:41 AM DEBUG: Running commandeer cmd: orfm  -m 96 /srv/projects/share/for_Joel/AB_C2_C3_C4_comb_assembly_bin4_hits.fa | hmmsearch -E 1e-5 --cpu 15 -o /dev/null --noali --domtblout /tmp/outer/AB_C2_C3_C4_comb_assembly_bin4_hits/AB_C2_C3_C4_comb_assembly_bin4_hits.hmmout.csv /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm -
08/07/2015 11:05:41 AM DEBUG: Running commandeer cmd: fxtract -H -X -f /tmp/graftm_readnamesL2GYCj  /srv/projects/share/for_Joel/AB_C2_C3_C4_comb_assembly_bin4_hits.fa > /tmp/_raw_extracted_reads.faMfB1Cg
08/07/2015 11:05:41 AM DEBUG: OrfM command chunk: orfm  -m 96 
08/07/2015 11:05:41 AM INFO: Aligning reads to reference package database
08/07/2015 11:05:41 AM DEBUG: Running commandeer cmd: hmmalign --trim /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm /tmp/outer/AB_C2_C3_C4_comb_assembly_bin4_hits/AB_C2_C3_C4_comb_assembly_bin4_hits_orf.fa | seqmagick convert --input-format stockholm - /tmp/for_conv_fileEhAYYE.fa
08/07/2015 11:05:41 AM INFO: Placing reads into phylogenetic tree
08/07/2015 11:05:41 AM DEBUG: Running commandeer cmd: pplacer -j 15 --verbosity 0 --out-dir /tmp/outer -c /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.refpkg /tmp/outer/combined_alignment.aln.fa
Traceback (most recent call last):
  File "/srv/whitlam/home/users/uqbwoodc/git/graftM/bin/graftM", line 231, in <module>
    graftm.run.Run(args).main()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 396, in main
    self.graft()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/run.py", line 361, in graft
    gpkg.taxonomy_info_path()
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/timeit.py", line 10, in timed
    result = method(*args, **kw)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/pplacer.py", line 112, in place
    jplace = self.pplacer(files.jplace_output_path(), args.output_directory, files.comb_aln_fa(), args.threads)
  File "/srv/home/uqbwoodc/git/graftM/bin/../graftm/pplacer.py", line 28, in pplacer
    extern.run(cmd)
  File "/srv/sw/extern/0.0.4/lib/python2.7/site-packages/extern/__init__.py", line 30, in run
    stdout)
extern.ExternCalledProcessError: Command pplacer -j 15 --verbosity 0 --out-dir /tmp/outer -c /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.refpkg /tmp/outer/combined_alignment.aln.fa returned non-zero exit status 1.
STDERR was: STDOUT was: Sequence length cut to 0 by pre-masking; can't proceed with no information.
```
Possibly because of the unusual hmmsearch output?
```
$ cat /tmp/outer/AB_C2_C3_C4_comb_assembly_bin4_hits/AB_C2_C3_C4_comb_assembly_bin4_hits.hmmout.csv 
#                                                                                   --- full sequence --- -------------- this domain -------------   hmm coord   ali coord   env coord
# target name               accession   tlen query name           accession   qlen   E-value  score  bias   #  of  c-Evalue  i-Evalue  score  bias  from    to  from    to  from    to  acc description of target
#       ------------------- ---------- ----- -------------------- ---------- ----- --------- ------ ----- --- --- --------- --------- ------ ----- ----- ----- ----- ----- ----- ----- ---- ---------------------
bin4_contig_71_93849_3_1167 -            326 DNGNGWU00001         -            250  2.6e-103  343.5   5.8   1   2  2.7e-107  2.6e-103  343.5   5.8     1   248    15   262    15   266 0.96 -
bin4_contig_71_93849_3_1167 -            326 DNGNGWU00001         -            250  2.6e-103  343.5   5.8   2   2      0.27   2.7e+03   -3.8   4.0   236   248   293   305   272   323 0.47 -
#
# Program:         hmmsearch
# Version:         3.1b2 (February 2015)
# Pipeline mode:   SEARCH
# Query file:      /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm
# Target file:     -
# Option settings: hmmsearch -o /dev/null --domtblout /tmp/outer/AB_C2_C3_C4_comb_assembly_bin4_hits/AB_C2_C3_C4_comb_assembly_bin4_hits.hmmout.csv --noali -E 1e-5 --cpu 15 /srv/sw/singlem/0.0.0.dev/singlem/../db/ribosomal_protein_S2_rpsB_gpkg/DNGNGWU00001.hmm - 
# Current dir:     /srv/projects/aom/aom-acetate/steve_analyses/binning/metabat_specific/current_bins
# Date:            Fri Aug  7 11:05:41 2015
# [ok]
```

**Comment by wwood** [comment]
Having trouble reproducing this, presumably fixed.
